function createfigure1(X1, Y1, Y2, Y3)
%CREATEFIGURE1(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 06-May-2016 11:02:11

% Create figure
figure1 = figure('Tag','TRAINING_PLOTTRAINSTATE','NumberTitle','off',...
    'Name','Neural Network Training Training State (plottrainstate), Epoch 11, Validation stop.');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log',...
    'Position',[0.13 0.709264705882353 0.775 0.215735294117647],...
    'XTickLabel','');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 11]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('gradient');

% Create title
title('Gradient = 0.01174, at epoch 11');

% Create semilogy
semilogy(X1,Y1,'Parent',axes1,'MarkerFaceColor',[1 0 0],'LineWidth',2);

% Create axes
axes2 = axes('Parent',figure1,'YScale','log',...
    'Position',[0.13 0.409632352941176 0.775 0.215735294117647],...
    'XTickLabel','');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 11]);
box(axes2,'on');
hold(axes2,'on');

% Create ylabel
ylabel('mu');

% Create title
title('Mu = 0.0001, at epoch 11');

% Create semilogy
semilogy(X1,Y2,'Parent',axes2,'MarkerFaceColor',[1 0 0],'LineWidth',2);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.775 0.215735294117647]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 11]);
box(axes3,'on');
hold(axes3,'on');

% Create ylabel
ylabel('val fail');

% Create xlabel
xlabel('11 Epochs');

% Create title
title('Validation Checks = 6, at epoch 11');

% Create plot
plot(X1,Y3,'Parent',axes3,'MarkerFaceColor',[1 0 0],'Marker','diamond',...
    'LineWidth',1,...
    'LineStyle','none');

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

